### ISSUE TITLE
Unclear how to do a "really clean" build

### ISSUE THREAD

**Issue by silvasean** [llvm/torch-mlir#1293]
I noticed that with source build of pytorch we end up caching some artifacts in build_tools/python_deploy (I think?). Can we make sure that we put all built artifacts in the build dir or have really clear docs about everything that gets built and how to clean it?

**Comment by powderluv** [comment]
If we run the Release build script we are exposed to:
https://github.com/llvm/torch-mlir/blob/c0630da678ea015ca8757340633c654d5539adac/build_tools/python_deploy/build_linux_packages.sh#L31

That said I think we can fix some of these docker issues by running them as the `$USER` instead of root.  I am trying to clean up and document the artifacts locations in the Docker PR https://github.com/llvm/torch-mlir/pull/1234

**Comment by silvasean** [comment]
Development.md now has instructions: https://github.com/llvm/torch-mlir/blob/main/docs/development.md#cleaning-up
