### ISSUE TITLE
Lowering failed: unsupported by backend contract: tensor with unknown rank

### ISSUE THREAD

**Issue by dellis23** [llvm/torch-mlir#1423]
I'm trying to develop a training example using `functorch`.  I'm starting with a small regression.  My first step before trying to get training working was to make sure I was able to compile the forward pass.

This is the example I'm using (training steps omitted for brevity):

```python
import numpy as np
import torch
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
import functorch

import torch_mlir
from functorch import make_fx

# Dataset
X, y = make_regression(n_features=3)
X, X_test, y, y_test = train_test_split(X, y)

# Weights
params = {
    'w': torch.zeros(X.shape[1:], dtype=torch.double),
    'b': torch.tensor(0., dtype=torch.double),
}

def forward(w, b, X):
    return torch.matmul(X, w) + b

linalg_on_tensors_mlir = torch_mlir.compile(
    make_fx(forward)(params['w'], params['b'], torch.tensor(X)),
    (params['w'], params['b'], torch.tensor(X)),
    output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,
    use_tracing=True)
```

This gives me the following error:

```python
TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
error: unsupported by backend contract: tensor with unknown rank
note: see current operation: %1 = "torch.tensor_static_info_cast"(%arg0) : (!torch.vtensor<[3],f64>) -> !torch.vtensor<*,f64>
note: this is likely due to a missing shape transfer function in shape_lib_gen.py
```

**Comment by silvasean** [comment]
@ramiro050 can you PTAL at this?

**Comment by dellis23** [comment]
I stripped it down a bit more to make it easier to reproduce:

```python
def forward(w, X):
    return torch.matmul(X, w)

args = (torch.tensor([1., 3., 4.], dtype=torch.double),
        torch.ones((75, 3), dtype=torch.double))
print(forward(*args))

print("Compiling with Torch-MLIR")
linalg_on_tensors_mlir = torch_mlir.compile(
    make_fx(forward)(*args),
    args,
    output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,
    use_tracing=True)
```

**Comment by ramiro050** [comment]
The issue is that `make_fx` turns the `torch.matmul` into [`torch.ops.aten.mv`](https://pytorch.org/docs/stable/generated/torch.mv.html), which does not have support in torch-mlir. This had not been an issue before because the TorchScript compiler turns `torch.matmul` into `torch.ops.aten.matmul`, which is why our [`matmul` tests](https://github.com/llvm/torch-mlir/blob/8d3ca887df5ac5126fa3fc2ec3546c6322a4d066/python/torch_mlir_e2e_test/test_suite/matmul.py#L74) pass.

Is the use of `make_fx` required? I just tested the `symbolic_trace` from [torch.fx](https://pytorch.org/docs/stable/fx.html), and if you use that the graph generated has the op `torch.ops.aten.matmul` rather than `torch.ops.aten.mv`.

**Comment by dellis23** [comment]
Re: `make_fx` required, I have no clue.  The [function itself](https://github.com/pytorch/pytorch/blob/06e0583fb0f62e27a52fb87f3dce3156cd2d0073/torch/fx/experimental/proxy_tensor.py#L582) doesn't seem to be documented anywhere.

Re: `symbolic_trace`, you tested on something functional?  It looks to me like it's only for `nn.Module`s.  When I try directly on a function, I get `RuntimeError: Could not get name of python class object`.

**Comment by silvasean** [comment]
I think we should add support for `torch.ops.aten.mv`. Or use a functorch-level decomposition of it back into matmul.

**Comment by dellis23** [comment]
Sounds good.  I'll work on that soon.

**Comment by ramiro050** [comment]
> Re: symbolic_trace, you tested on something functional? It looks to me like it's only for nn.Modules. When I try directly on a function, I get RuntimeError: Could not get name of python class object.

Yeah, I just replaced in your code `make_fx` with `symbolic_trace`, and the script runs without any errors:

```python
import numpy as np
import torch
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
import functorch

import torch_mlir
from functorch import make_fx
from torch.fx import symbolic_trace


def forward(w, X):
    return torch.matmul(X, w)

args = (torch.tensor([1., 3., 4.], dtype=torch.double),
        torch.ones((75, 3), dtype=torch.double))

print("Compiling with Torch-MLIR")
linalg_on_tensors_mlir = torch_mlir.compile(
    symbolic_trace(forward),
    args,
    output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,
    use_tracing=True)
```

**Comment by ramiro050** [comment]
According to the `torch.fx` docs, it should work on functions:

https://pytorch.org/docs/stable/fx.html#torch.fx.symbolic_trace

> Given an nn.Module or function instance root, this function will return a GraphModule constructed by recording operations seen while tracing through root.

**Comment by dellis23** [comment]
> According to the `torch.fx` docs, it should work on functions:
> 
> https://pytorch.org/docs/stable/fx.html#torch.fx.symbolic_trace
> 
> > Given an nn.Module or function instance root, this function will return a GraphModule constructed by recording operations seen while tracing through root.

Interesting.  That works for me now too, thanks.  I may have gotten my tabs mixed up with `make_functional`.

I'm not sure what the best direction to head here is.  What is the intended difference between `symbolic_trace` and `make_fx`, or how should a user know when to choose one over the other?

**Comment by ramiro050** [comment]
> What is the intended difference between symbolic_trace and make_fx, or how should a user know when to choose one over the other?

This might be a question better suited for pytorch. My understanding from playing around with the two is that `symbolic_trace` will trace your `forward` method, but if your method calls a submodule of your `torch.nn.Module`, that call will not be traced; it will simply be left as a `call_module` op. On the other hand, `make_fx` will trace through everything and generate a single graph with only `call_function`s in it. For example, given the following module definition:

```python
class MyModule(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = torch.nn.Linear(3, 3)

  def forward(self, x):
    return self.linear(x)
```

`symbolic_trace` will output:

```
graph():
    %x : [#users=1] = placeholder[target=x]
    %linear : [#users=1] = call_module[target=linear](args = (%x,), kwargs = {})
    return linear
```

and `make_fx` will output:

```
graph():
    %arg0_1 : [#users=1] = placeholder[target=arg0_1]
    %_param_constant0 : [#users=1] = get_attr[target=_param_constant0]
    %t : [#users=1] = call_function[target=torch.ops.aten.t.default](args = (%_param_constant0,), kwargs = {})
    %_param_constant1 : [#users=1] = get_attr[target=_param_constant1]
    %addmm : [#users=1] = call_function[target=torch.ops.aten.addmm.default](args = (%_param_constant1, %arg0_1, %t), kwargs = {})
    return addmm
```

This brings me to the second main difference. `symbolic_trace` will essentially capture the computation of the `forward` method as it was written. If `torch.matmul` is used in `forward`, you will see a `torch.matmul` in the generated graph. On the other hand, `make_fx` will actually generate a graph with only `torch.ops.aten` ops, which are the dispatch ops that get called internally, and the ops that torch-mlir actually cares about. For example, if you call `torch.sum(x, dim=1)`, `symbolic_trace` will generated a `call_function` to `torch.sum`, while `make_fx` will generate a `call_function` to `torch.ops.aten.sum.dim_IntList`. 

The last difference is that `symbolic_trace` works without specifying example inputs.

As to which one a user should use, in general I would prefer `make_fx` because it has higher changes of "just working". Since it gets rid of all the submodules and generates a single graph with only calls to `torch.ops.aten` ops, the only thing that can really go wrong when using it with torch-mlir is that an op is not yet supported. On the other hand, when using `symbolic_trace`, sometimes the module generated has some parts that are not `torch.jit.script`-able, or parts that are not supported in torch-mlir, such as submodules with weird control flow in them.

**Comment by silvasean** [comment]
@dellis23 can you maybe ask this on the #functorch-users channel on the PyTorch slack? I'd like to see what the PyTorch devs have to say about make_fx vs symbolic_trace -- in the end we just want the fx graph with the torch.ops.aten ops, but knowing the recommendations and pros/cons of each one would be useful.

**Comment by dellis23** [comment]
Copying pytorch's responses here for posterity.

> `make_fx` traces out the underlying ATen operators, while `symbolic_trace` traces out the torch API.
> 
> As for when you should use one vs. the other... `symbolic_trace` is best suited for "metaprogramming" type transforms.
>
> It's also more mature in general, and so folks have used it for compiler lowering as well.
>
> `make_fx` allows you to capture things like backwards pass though, and in general is probably better suited for compilation purposes.

I also asked about using `symbolic_trace` with `functorch.grad`, since I was having issues with it.

> no, `symbolic_trace` isn't intended to work with `functorch.grad`

So for the example I'm working on (training), it seems like using `make_fx` will be necessary, along with adding support for `mv`.

**Comment by silvasean** [comment]
Can you make_fx the symbolic_trace? Then you can get the best of both worlds.

**Comment by dellis23** [comment]
How do you imagine that working?  `symbolic_trace` the loss function and forward function, then wrap the grad in `make_fx`?  If so, I can give it a shot, but I don't think it really helps for the end goal of making this something a user can use (e.g. it seems like a higher level tool like `iree-torch` would not be usable by a user without rewriting their model and doing manual tracing in the "correct" place).

**Comment by erl4ng** [comment]
> As to which one a user should use, in general I would prefer `make_fx` because it has higher changes of "just working" with torch-mlir.

Can you elaborate :-) 

not sure if you mean that `make_fx` has higher chances of just working...?

**Comment by dellis23** [comment]
Solved by https://github.com/llvm/torch-mlir/pull/1453

**Comment by ramiro050** [comment]
> Can you elaborate :-)
> 
> not sure if you mean that `make_fx` has higher chances of just working...?

Sure! So what's nice about `make_fx` is that it always returns a graph with *only* dispatch ops, which are the ops that torch-mlir is interested in. This means that importing a graph created by `make_fx` should in theory always work. If there is an error, it will almost always be due to a dispatch op not having support in torch-mlir.

On the other hand, `symbolic_trace` could capture several things that can cause trouble in torch-mlir. Since `symbolic_trace` [does not trace through calls to submodules](https://pytorch.org/docs/stable/fx.html#leaf-modules), if the submodule contains data-dependent control flow or loops, or other unsupported TorchScript constructs, those will get imported into torch-mlir, causing problems.

Hope this helps, @erl4ng
