### ISSUE TITLE
Unable to compile functions with dictionary inputs

### ISSUE THREAD

**Issue by dellis23** [llvm/torch-mlir#1425]
I've tried a few approaches.  Not sure if any of these _should_ work or if I'm missing the correct way altogether.

```python
import torch
from torch import Tensor
import torch_mlir
from functorch import make_fx
from typing import Dict

def dict_fn(x: Dict[str, Tensor]):
  return x['a'] * 2.0

print(dict_fn({'a': torch.tensor(3.0)}))

linalg_on_tensors_mlir = torch_mlir.compile(
    make_fx(dict_fn)({'a': torch.tensor(3.0)}),
    {'a': torch.tensor(3.0)},
    output_type=torch_mlir.OutputType.LINALG_ON_TENSORS)
```

[Output](https://gist.github.com/dellis23/5e661e642961732471010392a76883ea)

```python
import torch
from torch import Tensor
import torch_mlir
from functorch import make_fx
from typing import Dict

@torch.jit.script
def dict_fn(x: Dict[str, Tensor]):
  return x['a'] * 2.0

print(dict_fn({'a': torch.tensor(3.0)}))

linalg_on_tensors_mlir = torch_mlir.compile(
    make_fx(dict_fn)({'a': torch.tensor(3.0)}),
    {'a': torch.tensor(3.0)},
    output_type=torch_mlir.OutputType.LINALG_ON_TENSORS)
```

[Output](https://gist.github.com/dellis23/1a64b686934166bec4cbaf80215bf3bc)

```python
import torch
from torch import Tensor
import torch_mlir
from functorch import make_fx
from typing import Dict

def dict_fn(x: Dict[str, Tensor]):
  return x['a'] * 2.0

print(dict_fn({'a': torch.tensor(3.0)}))

linalg_on_tensors_mlir = torch_mlir.compile(
    make_fx(dict_fn)({'a': torch.tensor(3.0)}),
    {'a': torch.tensor(3.0)},
    output_type=torch_mlir.OutputType.LINALG_ON_TENSORS,
    use_tracing=True)
```

[Output](https://gist.github.com/dellis23/1293ee6459ddfb9b52a983aa2a1091bb).  This seems like it's the closest to correct, and perhaps `torch-mlir` isn't passing along the necessary annotations.  I'm not sure though.  This was the same error torch itself gave when trying to trace before I added the type annotations.

I've tried many other variations, but I'm not sure they're sensical.

**Comment by ramiro050** [comment]
`torch_mlir.compile` only supports tensors for the `example_inputs` arg:

https://github.com/llvm/torch-mlir/blob/8d3ca887df5ac5126fa3fc2ec3546c6322a4d066/python/torch_mlir/__init__.py#L139

https://github.com/llvm/torch-mlir/blob/8d3ca887df5ac5126fa3fc2ec3546c6322a4d066/python/torch_mlir/__init__.py#L135

This is true not just for the python API, but torch-mlir as a whole. Inputs other than tensors are not supported. Part of the reason is that many inputs types don't have a clear path to the backend dialects that torch-mlir is targeting. So python objects like dicts and lists are expected to be constants so that torch-mlir can fold them away during lowering before reaching the backend contract.

For examples of how to get dicts into torch-mlir, there are the two lit tests:

https://github.com/llvm/torch-mlir/blob/main/test/python/importer/jit_ir/node_import/dict.py

https://github.com/llvm/torch-mlir/blob/main/test/python/importer/jit_ir/ivalue_import/dict.py

I have not played with dicts before, so I'm not sure if there is folding support for them as you lower to a backend dialect, but importing them into the torch dialect should work, since the tests above pass.

**Comment by dellis23** [comment]
To make sure I understand, the two links are illustrating that dicts can be 1) stored on the module itself and 2) returned as outputs, but not sent as inputs?

I'm wondering what the best way to communicate this to users would be without making the intro readme too bloated.  Perhaps improving the error message and pointing to a more specific section of documentation would be good.  Right now, the error that the user ultimately gets seems completely incorrect:

```
RuntimeError: Type 'Tuple[str]' cannot be traced. Only Tensors and (possibly nested) Lists, Dicts, and Tuples of Tensors can be traced
```

(Since `torch-mlir` _doesn't_ support a dict of tensors as an input).

**Comment by silvasean** [comment]
This is a classic "you call a thing that calls a thing and that thing has the error and we don't bother to massage it to make it better" situation. I think we can solve this with just an "elif" here to catch the "neither Tensor nor TensorPlaceholder" case: https://github.com/llvm/torch-mlir/blob/8d3ca887df5ac5126fa3fc2ec3546c6322a4d066/python/torch_mlir/__init__.py#L200

**Comment by ramiro050** [comment]
> To make sure I understand, the two links are illustrating that dicts can be 1) stored on the module itself and 2) returned as outputs, but not sent as inputs?

Yes. However, this is only true for importing the TorchScript into torch-mlir. Once you try to lower to the backend contract, returning a dict will fail, since none of the backend, AFAIK, support returning a dict.
