### ISSUE TITLE
[RFC] Custom ops support

### ISSUE THREAD

**Issue by silvasean** [llvm/torch-mlir#1462]
Hey folks, custom ops has been a common feature request, and I'd like to share a design that we've been thinking about.

Let's talk first about the functionality we want to unlock for users. Generally speaking, custom ops are a way to "tunnel" information from the frontend to the backend. This can be something like a custom fusion, or something more advanced, like a representation of quantization or sparsity. Note that ops can also carry various different types of information, such as `!torch.int`, `!torch.string`, etc. (which we would generally need to be constrained to statically known values to be useful in the compiler). So an op like `my.custom_quantize %foo, %quantization_info, ...` etc. could actually carry a fairly elaborate representation of quantization/sparsity/etc. in the `%quantization_info` string.

The key requirement here is the desire to support new ops without recompiling Torch-MLIR. We've had some [initial efforts](https://github.com/llvm/torch-mlir/pull/1355) in the custom op direction, but they always required recompiling Torch-MLIR. Put another way, the goal is to generalize the current way of handling ops so that there is no "hardcoded C++" for each op. Here by **"support new ops" we really mean lowering to the backend contract** (see [architecture.md](https://github.com/llvm/torch-mlir/blob/main/docs/architecture.md)). Lowering to Linalg/etc. generally is out of scope of this effort, since a different set of technology is involved.

In our longer-term roadmap (see [slide](https://docs.google.com/presentation/d/1YXRi0B9sGYjs7m4SS4TZAZeZiN4kOOUPttC_5rFQzr4/edit?resourcekey=0-RXKEOmWsvLoEiS8uMwLFJw#slide=id.gfee1e8ed26_0_14)) of aligning with TorchDynamo and upstream PyTorch, we will directly import into the backend contract, so all of this work on custom ops will be obsoleted. But the indication is that this longer-term roadmap will take 1-2 years to fully pan out, while we want to unlock this user requirement in a shorter timeframe (ideally months).

------------------------------------

When lowering to the backend contract, there are 4 main responsibilities (see [architecture.md](https://github.com/llvm/torch-mlir/blob/main/docs/architecture.md#the-backend-contract)):

- All tensors have been converted to value semantics.
- All tensors have at least a known number of dimensions (i.e. rank), and ideally also have a precise size for each dimension.
- All tensors have a known dtype.
- Certain ops have been decomposed to make them easier to handle (this is configurable).

Let's go over these one by one:

1. Conversion to value semantics. This is a very tricky conversion (see MaximizeValueSemantics [pass](https://github.com/llvm/torch-mlir/blob/main/lib/Dialect/Torch/Transforms/MaximizeValueSemantics.cpp), [test](https://github.com/llvm/torch-mlir/blob/main/test/Dialect/Torch/maximize-value-semantics.mlir)). From a design perspective, I don't see any option other than to require all custom ops be value-semantic. This seems like it will be enough for the use cases that the community has presented so far.
2. Shape inference. We already do this with the [Shape Library](https://github.com/llvm/torch-mlir/blob/main/docs/shape_lib.md). The shape functions are [written in a Python script](https://github.com/llvm/torch-mlir/blob/main/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py) that is then used to generate the shape functions as MLIR. Since the shape functions are represented as MLIR snippets, we can (conceptually) already load new shape functions from a .mlir file on the side without recompilation. So there is no big architectural change here.
3. Dtype inference. This currently happens in a hardcoded C++ pass [RefineTypes](https://github.com/llvm/torch-mlir/blob/8f608c048d0fb9a07833a741ffc23eeaf45cd340/lib/Dialect/Torch/Transforms/RefineTypes.cpp#L1). This pass needs to be rewritten to not require recompiling to support new ops. We can follow the same design as the shape library -- reify, abstractly interpret, drop. This will be a total rewrite of this component.
4. Decompositions. We currently have thousands of lines of decompositions in [DecomposeComplexOps](https://github.com/llvm/torch-mlir/blob/8f608c048d0fb9a07833a741ffc23eeaf45cd340/lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp#L1). We should be able to follow a similar approach as the shape library, and basically just replace `aten.foo ...` with `call @aten.foo$decomposition ...`. PyTorch already maintains many such decompositions ([here](https://github.com/pytorch/pytorch/blob/master/torch/_decomp/decompositions.py) and [here](https://github.com/pytorch/pytorch/tree/master/torch/_refs)), so this will also allow unifying efforts with those upstream, which is a big win by itself.

The overall design that we are left with is that we need to generalize the shape library infrastructure to encompass dtype refinement rules and decompositions. The system could look something like this, which is a generalization of [shape_lib_gen.py](https://github.com/llvm/torch-mlir/blob/8f608c048d0fb9a07833a741ffc23eeaf45cd340/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/shape_lib_gen.py#L319):

```python
def aten〇tanh〡shape(self: List[int]) -> List[int]:
    return upstream_shape_functions.unary(self)
def aten〇tanh〡dtype(self_shape: List[int], self_dtype: int) -> int:
    return dtype_functions.unary(self_shape, self_dtype)
# This is just an example -- we would probably not want this decomposition for tanh.
# Decompositions would be optional, but if provided would be available for use.
def aten〇tanh〡decomposition(self: torch.Tensor) -> torch.Tensor:
    exp, expn = torch.exp(self), torch.exp(-self)
    return (exp - expn) / (exp + expn)
```

We would process this and generate a .mlir file similar to the current shape library, which would be usable to service the goals listed above. When users want to support custom ops, they will write such functions, and use tools provided by Torch-MLIR to import that into a .mlir file and then include those for the passes that need them.

-------------------------

The main work items here are:

- Generalize shape library testing framework to work with dtype functions and decompositions
- Migrate PyTorch’s type promotion logic (currently hardcoded in refine types) to Python so that dtype functions can use it
- Generalize (and potentially improve) the abstract interpretation code from the shape library to also work with dtype calculations and decompositions
- Create an interface for users to load their custom ops: `$ torch-mlir-opt -pass-pipeline='torchscript-module-to-torch-backend-pipeline{extra-library=my_custom_ops.mlir}'`
--------------------------------

Thoughts or feedback?

**Comment by powderluv** [comment]
I assume we will also add the python wrapper to point to the custom ops from python ?

**Comment by ramiro050** [comment]
> I assume we will also add the python wrapper to point to the custom ops from python ?

Yeah, the Torch-MLIR Python API will have a way to specify custom ops file.

**Comment by makslevental** [comment]
>Create an interface for users to load their custom ops: $ torch-mlir-opt -pass-pipeline='torchscript-module-to-torch-backend-pipeline{extra-library=my_custom_ops.mlir}'

Another way to implement this is to enable/allow users to provide these shape and dtype functions in the same module that they provide their `func.func @forward(...`. I show a minimal implementation in https://github.com/llvm/torch-mlir/pull/1959.

**Comment by ramiro050** [comment]
> Another way to implement this is to enable/allow users to provide these shape and dtype functions in the same module that they provide their `func.func @forward(...`. I show a minimal implementation in #1959.

I have a couple of questions. The first is regarding the user experience. How would the interface for users work to add their dtype functions into their module? Ideally we want to avoid users having to directly modify an MLIR module at the Python level to attach more MLIR.

The second question is regarding how things are expected to work internally in torch-mlir. Carrying around the shape+dtype functions in the module means that now every pass in torch-mlir will also be spending time applying to shape+dtype functions, which would increase lowering time (might not be a concern in practice, but it's something to think about). The second issue I foresee is that shape+dtype functions are not required to satisfy the backend contract. Carrying around the functions in the module would mean that we now have to have special casing in the LowerToBackendContract pass to not consider those functions. Lastly, carrying around many shape+dtype functions would make reading MLIR dumps harder, since passes that have nothing to do with type refinement would be also dumping the shape+dtype functions, worsening the debugging experience. 

What are the downsides from the current proposed design you're trying to solve with this new design?

**Comment by makslevental** [comment]
>What are the downsides from the current proposed design you're trying to solve with this new design?

There is no current design - there is only an idea for an API.

>Create an interface for users to load their custom ops: `$ torch-mlir-opt -pass-pipeline='torchscript-module-to-torch-backend-pipeline{extra-library=my_custom_ops.mlir}'`

I can certainly envisage how that would be implemented but a vision does not equate to a design. 

Next;

>Ideally we want to avoid users having to directly modify an MLIR module at the Python level to attach more MLIR

There's some premise/assumption implicit here that I don't understand/agree with - there's simultaneously mentions of the python API:

>[Torch-MLIR's only supported "stable" interface is the `torch_mlir.compile`](https://github.com/llvm/torch-mlir/pull/1959#issuecomment-1479711867)

and the proposal here (re: going through `torch-mlir-opt`). So which is it? Is `torch-mlir` Python first or `CLI` first? Regardless, my answer is simple: the entire "raison d'etre" for having IR is so you can pass textual source between passes (instead _requiring_ transforming one single AST), i.e., to decouple passes for exactly this kind of thing - run a pass, fiddle, run another pass, etc. Whether that fiddling happens through the Python bindings or by handwriting a `my_custom_ops.mlir` is irrelevant (how do you expect people to conjure this `my_custom_ops.mlir` if not through Python anyway...). Indeed it wouldn't matter to me at all _if the implementation of this API existed today_ because I would just generate those shape functions using Python bindings and `print(module)` and then pass them that to `extra-library` and you'd never hear me from that I broke the covenant that things shouldn't be done using Python.

Next;

>The second issue I foresee is that shape+dtype functions are not required to satisfy the backend contract.

Ah but they are - again I would not have gone monkeying around _if I didn't have to_: [LowerToBackendContract.cpp#L91](https://github.com/llvm/torch-mlir/blob/eb74014dd829a34f722969aed3872e2baf2491b4/lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp#L91). 

Finally;

>Carrying around the shape+dtype functions in the module means that now every pass in torch-mlir will also be spending time applying to shape+dtype functions, which would increase lowering time (might not be a concern in practice, but it's something to think about)... Lastly, carrying around many shape+dtype functions would make reading MLIR dumps harder...

Sure and we can weigh the costs benefits of increased compile times and decreased legibility against _the complete inability of users to lower models which include currently unsupported ops_.

**Comment by silvasean** [comment]
Hey folks, it looks like the main stakeholders here are happy with pushing this feature through as we have specced here. I created another issue to help shepherd this work to completion at a detailed work level. Let's move further discussion there: https://github.com/llvm/torch-mlir/issues/1963

**Comment by igozali** [comment]
Apologies for the very silly question, but wondering where I can find the rationale/RFC/discussion for using the unicode character 〇 in the function names above?

**Comment by powderluv** [comment]
Its a cust〇m 〇p :)

**Comment by powderluv** [comment]
And I think can be closed now that it is implemented.

**Comment by ramiro050** [comment]
@igozali, there is some information about why use the character here:

https://github.com/llvm/torch-mlir/blob/449cfb83755b97115ba7c3c27b0efdb03415810b/docs/adding_abstract_interpretation_functions.md?plain=1#L26-L27

and the rationale for using the entire operator name for each function [here](https://github.com/llvm/torch-mlir/blob/449cfb83755b97115ba7c3c27b0efdb03415810b/docs/abstract_interp_lib.md#use-of-full-operator-signatures).

In short, we wanted to keep the full operator name with namespace information in a way that would then be easily parsable by the [Python script that generates the MLIR snippets](https://github.com/llvm/torch-mlir/blob/449cfb83755b97115ba7c3c27b0efdb03415810b/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/library_generator.py#L241), so that in MLIR it is easy to know which abstract interpretation function goes with which op. If we had resorted to using normal characters (letters and `_`), there would be several ambiguous cases, because some ops have `_` in their names.
