### ISSUE TITLE
Throw better error message when not returning a tensor or tuple of tensors

### ISSUE THREAD

**Issue by dellis23** [llvm/torch-mlir#1491]
See https://github.com/llvm/torch-mlir/issues/1471 for background

**Comment by dellis23** [comment]
@silvasean 

Re: the case we talked about today, of returning a single-item tuple.  The following error is thrown:

```python
Traceback (most recent call last):
  File "/usr/local/google/home/danielellis/torch-mlir/repro.py", line 40, in <module>
    main()
  File "/usr/local/google/home/danielellis/torch-mlir/repro.py", line 32, in main
    linalg_on_tensors_mlir = torch_mlir.compile(
  File "/usr/local/google/home/danielellis/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 274, in compile
    run_pipeline_with_repro_report(
  File "/usr/local/google/home/danielellis/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
error: failed to legalize unresolved materialization from '!torch.tuple<tensor>' to '!torch.tensor' that remained live after conversion
note: see current operation: %2 = "builtin.unrealized_conversion_cast"(%1) : (!torch.tuple<tensor>) -> !torch.tensor
note: see existing live user here: "func.return"(%2) : (!torch.tensor) -> ()
```

We talked about putting another check just before the success [here](https://github.com/llvm/torch-mlir/blob/0af55781aede053f32d2b618f0f6d36d875fd908/lib/Dialect/Torch/Transforms/AdjustCallingConventions.cpp#L261).  We never actually reach this line, however.  We end up failing in [the check before](https://github.com/llvm/torch-mlir/blob/0af55781aede053f32d2b618f0f6d36d875fd908/lib/Dialect/Torch/Transforms/AdjustCallingConventions.cpp#L258-L260), in the call to `applyPartialConversion`.

**Comment by ramiro050** [comment]
I think the issue is this type conversion:

https://github.com/llvm/torch-mlir/blob/0af55781aede053f32d2b618f0f6d36d875fd908/lib/Dialect/Torch/Transforms/AdjustCallingConventions.cpp#L196-L201

It should not succeed if the tuple only has one element in it.

Another point that might be important to look at is:

https://github.com/llvm/torch-mlir/blob/0af55781aede053f32d2b618f0f6d36d875fd908/lib/Dialect/Torch/Transforms/AdjustCallingConventions.cpp#L78-L81

That conversion should also result in an error if the tuple has one element in it.

**Comment by ramiro050** [comment]
Actually, I think the conversions should simply return the tuple type when the tuple has one element, rather than throwing an error, since there are valid cases where we should have a function returning a single element tuple. For example:

```python
def foo(x):
    return (x,)

def forward(x):
    return foo(x)[0]
```

**Comment by silvasean** [comment]
> Actually, I think the conversions should simply return the tuple type when the tuple has one element, rather than throwing an error, since there are valid cases where we should have a function returning a single element tuple. For example:

Strictly speaking, we need to distinguish between externally-callable functions and private functions. AdjustCallingConventions is only about externally-callable functions, and for those, a single-element tuple is not a valid return type (it will not satisfy the backend contract).

**Comment by ramiro050** [comment]
> AdjustCallingConventions is only about externally-callable functions, and for those, a single-element tuple is not a valid return type (it will not satisfy the backend contract). 

Right, that's a good point. I was thinking about the example I mentioned above because of this lit test replacing `!torch.tuple<tensor, tensor>` with `!torch.tuple<tensor>`: https://github.com/llvm/torch-mlir/blob/c97df38e3e39353410b3fd057118caaae26be2d5/test/Dialect/Torch/adjust-calling-conventions.mlir#L95-L99. But yeah, in that test case, because both functions are public, it makes sense that both should be expected to not return a single element tensor.

> Strictly speaking, we need to distinguish between externally-callable functions and private functions. 

Is this something that is already being done? The `AdjustCallingConventions` seems to apply to all `func::FuncOp`s in the module. (Although we do inline things before that pass, which gets rid of private functions that might return a single element tuple).

**Comment by silvasean** [comment]
> Is this something that is already being done? The `AdjustCallingConventions` seems to apply to all `func::FuncOp`s in the module. (Although we do inline things before that pass, which gets rid of private functions that might return a single element tuple).

I suspect what we are doing now "happens to be sound", but yeah, AdjustCallingConventions probably should be explicitly checking public/private in theory.
