### ISSUE TITLE
[RFC] Supporting `ChannelsLast` memory format for `aten.clone` op

### ISSUE THREAD

**Issue by vivekkhandelwal1** [llvm/torch-mlir#1829]
Hi @ramiro050 @silvasean, I encountered an instance of a clone op in the model IR, where the memory_format arg is set to `ChannelsLast`. Can we support this in Torch-MLIR or is there a way to eliminate/canonicalize this in the IR?

Here's an instance: https://gist.github.com/vivekkhandelwal1/ffba6fbbfa72c44e79639bec253d0910#file-sd_snippet_torch_ir-mlir-L656

**Comment by ramiro050** [comment]
My initial thought is that we can treat it the same way as we've treated other `memory_format` flags like `contiguous_format`: ignore it. 

The flag seems to just change the stride and memory layout of the tensor, but the result tensor still *looks* the same to all the other pytorch ops (not counting ops that explicitly modify stride information, which we don't handle in torch-mlir at the moment). Therefore, ignoring it should not affect the correctness of the graphs generated by torch-mlir.

In addition, the MLIR `tensor` type by design [does not specify runtime representation](https://mlir.llvm.org/docs/Dialects/Builtin/#rankedtensortype) of the tensors. So if we currently ignore `contiguous_format`, there is no reason why we should handle `channels_last` differently.

There is the ability to specify attributes in the `tensor` type that could capture memory layout specifications that backend compilers can then use if they want to, but that would require some changes in torch-mlir to pipe this through.

@silvasean, do you have any thoughts on this?

**Comment by silvasean** [comment]
That sounds correct to me. The channels_last sets the stride information and we do not model that, so there is no way to get it through. Generally speaking, downstream compilers should know if channels_last is better for their hardware (and do the relevant transpose themselves), so there isn't much reason for users to specify it or for us to propagate it. That's basically an artifact of PyTorch's eager mode where the user has to manually do thing that the compiler should really be doing.
