### ISSUE TITLE
Participate in NPBench

### ISSUE THREAD

**Issue by tbennun** [llvm/torch-mlir#216]
First of all, awesome project!

It would be interesting to see the results of the NPComp infrastructure vs. other python compilers, such as Numba, on scientific python apps. [NPBench](https://github.com/spcl/npbench) has a wide variety of HPC and computational science apps written in numpy. It'd be great if you had an implementation/results there!

**Comment by silvasean** [comment]
Thanks for the information! We probably won't be participating for a while, because our [roadmap](https://github.com/llvm/mlir-npcomp/blob/main/docs/roadmap.md) has pivoted towards PyTorch support as a first priority, and we are likely to come back around later and layer the vanilla Python/numpy compiler on top of the infrastructure we build for that.

Thanks for the link to NPBench though!!! It seems like a super useful corpus of programs -- I was looking for something like that! Looking forward to participate in the future!
