### ISSUE TITLE
Is it possible to build npcomp with a prebuilt llvm-project ?

### ISSUE THREAD

**Issue by edimetia3d** [llvm/torch-mlir#271]
Hi,

I'm thinking to contribute some build feature to the npcomp cmake build script, and want some advice before doing it.

Here are our problem. 

We developed a  project Foo, which will use mlir's python binding from a modified llvm-project, this llvm-project is updated with upstream, and shipped  to us as a prebuilt library.
Now , we want also to use npcomp in our project, but the current build process need to build llvm from source, and will create a bundled mlir pacakge, so this just doesn't work with us.

I think npcomp should be able to work in a more decoupled way, what I want to do are: 
1. Build npcomp with a prebuilt llvm-project, with something like `cmake -DLLVM_INSTALL_ROOT` 
2. Re-arrange code/file to remove the "python_packages/npcomp_core/mlir", so the `import mlir` will import milr from the prebuilt mlir , and `import npcomp` will just import things npcomp needed

Is it fine to do so?  

Sincerely

**Comment by marbre** [comment]
What you have in mind sounds similar to what the [standalone example](https://github.com/llvm/llvm-project/tree/main/mlir/examples/standalone) does. This is also how [emitc](https://github.com/iml130/mlir-emitc) is build (the dialect is already available upstream but some remaining parts are not). I am not sure if there is anything special about the python bindings, but what you have in mind should be possible.
I recently asked @stellaraccident quite the same question with view on [iree-dialects](https://github.com/google/iree/tree/main/llvm-projects/iree-dialects). Happy to help out after we discussed our options :)

**Comment by silvasean** [comment]
We used to build that way, but just changed away from it. @stellaraccident can weigh in on the cost of supporting the configuration you propose.

**Comment by stellaraccident** [comment]
Python based MLIR projects are special (not special from a Python sense): you can't have a stable configuration where you have binary C++ dependencies across packages. While it can be arranged with some effort for intimately connected projects, trying to just smash two projects together is not going to work. The way this is headed is that the `import mlir` in npcomp will go away and it will just be `import npcomp.ir`, `import npcomp.dialects`, etc.

So there are two questions here:

a) Can we make things work with an installed LLVM, vs a source dep: Yes, but it will not work right now. We need to export the Python sources from the MLIR python build rules, and I haven't taken the time to do it. The complexity of it lies somewhere between easy and hard, and I was hoping to have a good example/need to work from. It's all laid out properly as CMake targets with properties... it's just CMake. Probably a day or two of work if I were going to do it with the state I have.

b) Can Foo project mix and match Python bindings from multiple sources (i.e. cross dependencies across `import mlir`, `import npcomp`, `import foo` working together at the binary level): No. You can create Foo as a super-project that includes MLIR+NPCOMP+Foo_stuff, package and use that, but it needs to land in its own namespace (i.e. `foo.ir`, `foo.dialects`, etc). We just got that kind of relocatability/embedding modality [working this morning](https://github.com/google/iree/pull/6668), and I haven't come back and reworked npcomp to be embeddable yet. The npcomp python code needs some reorganization too so that it uses namespace packages and doesn't squat on its names.

There is also a modality that you may or may not be looking for but is possible (with a bit of cleanup -- other projects are doing this): include the Python bindings for npcomp's dialects and passes in your project and leave the rest of "npcomp" behind. 

Not sure exactly what your use case is... there are various ways to slice things so long as we don't cross unstable binary boundaries. You're definitely pushing on things that are still raw and in-flight. It's basically been a volunteer effort between me and someone on the circt project getting it to this point.

If you're interested in helping with (a), most of the work will be upstream, and we should continue on LLVM's discourse. If you're looking to do (b), then we lack a good canonical example and there are undone threads that contributions are welcome on. If looking to embed dialects/passes from npcomp in your project, we can just continue here. There will be a bit of npcomp work to enable it, but we have examples of other projects that do this.

It sounds like in all universes, you need (a) resolved.

**Comment by stellaraccident** [comment]
One thing to remember is that MLIR's python API is not a "product": It is a tool for building products that happens to be built as part of MLIR for in-tree demo purposes. NPCOMP is currently set up as a product that is used on its own. It can be organized better for use as a library for building other things, but that is all work that hasn't been done yet.

**Comment by edimetia3d** [comment]
@marbre @silvasean @stellaraccident 

This problem seems more complicated than I thought.
I will conduct a more in-depth investigation on your information in these days, before I will reply.

Many thanks

**Comment by edimetia3d** [comment]
@stellaraccident 

## Our case is like this.
We have implemented our own out-of-tree dialect Foo and a backend to lower Foo to machine code.
Now we want to leverage npcomp's pytorch frontend, so we could just add some code to convert the Torch dialect to Foo dialect to support pytorch, it's like the code below
 
```python
import torch
import torch_mlir
import foo
mb = torch_mlir.ModuleBuilder()
do_sth_update_mb(mb)

foo_moudle=foo.convert_aten_to_our_dialect(mb.module)
do_foo_compile(foo_moudle,args)

```

So, like you advised , Foo depends on both llvm-project and npcomp,  both project are submodule of Foo, and the "build from prebuilt llvm library" issue occurs here.

Technically, Foo doesn't use mlir's python binding at all, most of our job is done with C++,  and we just use pybind11 to export some C++ interface to python.  So, the "import mlir" issue is not so important to us. It is mainly a concern about packaging. 

Not all python package under "mlir" are namespace package, so, when there were multiple "mlir" package in python's path, there might be some issue about module search order. So I thought no bundled mlir would be a better solution.  ​

And I  was thinking that NPCOMPPythonCAPI seems just the MLIRPythonCAPI with some "extra files", we might be able to build the "extra files" into an "extra_lib", and then make "_npcomp" link against the "extra_lib", after this, ` import prebuilt-mlir` plus `import _npcomp` should be equal to `import bundled-mlir`


## New Questions

1. You have mentioned 

> The way this is headed is that the `import mlir` in npcomp will go away and it will just be `import npcomp.ir`, `import npcomp.dialects`, etc.

Does this mean the bundled "mlir" will be gone someday?



2. About he question (a), if I understand correctly , we  need to export some C++ binary target  in a prebuilt llvm project. And as far as I know, these target are mainly involved in "MLIRPythonSources", which is used by `add_mlir_python_common_capi_library` and `add_mlir_python_modules`.

**Comment by stellaraccident** [comment]
> @stellaraccident
> 
> ## Our case is like this.
> We have implemented our own out-of-tree dialect Foo and a backend to lower Foo to machine code.
> Now we want to leverage npcomp's pytorch frontend, so we could just add some code to convert the Torch dialect to Foo dialect to support pytorch, it's like the code below
> 
> ```python
> import torch
> import torch_mlir
> import foo
> mb = torch_mlir.ModuleBuilder()
> do_sth_update_mb(mb)
> 
> foo_moudle=foo.convert_aten_to_our_dialect(mb.module)
> do_foo_compile(foo_moudle,args)
> ```
> 
> So, like you advised , Foo depends on both llvm-project and npcomp, both project are submodule of Foo, and the "build from prebuilt llvm library" issue occurs here.
> 
> Technically, Foo doesn't use mlir's python binding at all, most of our job is done with C++, and we just use pybind11 to export some C++ interface to python. So, the "import mlir" issue is not so important to us. It is mainly a concern about packaging.

Ok, so I understand clearly: either your Foo project needs to use npcomp's dialects or npcomp needs to be able to somehow include Foo and its transformations. And they all depend on llvm-project. Correct?

For including npcomp C++ code in another project, we can fairly easily do what others have done and let npcomp be included either standalone or as an LLVM_EXTERNAL_PROJECT into Foo. Then you just `#include "npcomp/Dialect/..." and reference the target and go. We're not ready to support out of tree use of the Python side (or the PyTorch integration) in that mode but can in the future -- it is just build and project organization work that needs to be done (and is a bit finicky). 

Enabling npcomp C++ components to be included in an out of tree project in this way can be done today and would be accepted. There are examples in circt and elsewhere to set it up in this way.

> 
> Not all python package under "mlir" are namespace package, so, when there were multiple "mlir" package in python's path, there might be some issue about module search order. So I thought no bundled mlir would be a better solution. ​

We did put work in to make sure that everything that should be separable is a namespace package, but may have missed some things. As an example, `mlir` and `mlir.dialects` are namespace packages because we expect those to have contributions from multiple projects. But `mlir.dialects.linalg` is not a namespace package because it is singular.

If there are things that need reworking, those are good changes to make. We've already done a bunch of those.

> 
> And I was thinking that NPCOMPPythonCAPI seems just the MLIRPythonCAPI with some "extra files", we might be able to build the "extra files" into an "extra_lib", and then make "_npcomp" link against the "extra_lib", after this, ` import prebuilt-mlir` plus `import _npcomp` should be equal to `import bundled-mlir`

Maybe some day. Today, MLIR is not safe for linking across multiple DSOs. There may be others but the primary outstanding issues I know of are here: https://llvm.discourse.group/t/more-work-needed-for-typeid-duplication-help-wanted/4041/3

In general, it is better for deployment to "statically" link such things (even if into a DSO). That way, you can use hidden visibility, which results in significantly smaller binaries. I suspect that even if we fix the bugs and and make cross-DSO linking more robust, we'll still want the primary way to use these things to be via such monolithic deps for deployment. That's not to say you can't do something different if your use case calls for it.

> 
> ## New Questions
> 1. You have mentioned
> 
> > The way this is headed is that the `import mlir` in npcomp will go away and it will just be `import npcomp.ir`, `import npcomp.dialects`, etc.
> 
> Does this mean the bundled "mlir" will be gone someday?

Yes, and this is how we have IREE set up (i.e. it is all under the `iree.` namespace package, including `iree.ir`, `iree.dialects`, etc): there is no re-export of the `mlir` namespace. I just didn't have time in my first round to update npcomp accordingly. Probably in September as I'm on leave for a couple of weeks now.

> 
> 1. About he question (a), if I understand correctly , we  need to export some C++ binary target  in a prebuilt llvm project. And as far as I know, these target are mainly involved in "MLIRPythonSources", which is used by `add_mlir_python_common_capi_library` and `add_mlir_python_modules`.

If you'd like my recommendation on how to make progress immediately, it would be similar to what we do with IREE: interop via ASM (i.e. have npcomp generate MLIR assembly from your torch programs and then import/compile/do whatever that on your Foo side). That will still require you to make some changes to NPCOMP's main CMake file to allow it to build against an installed MLIR (and disable its Python bindings until we get that going) so you can include its dialects in your project, but those should be pretty mechanical. Until we get all of the cross project issues worked out, this would let you have something that can work, and you can make progress. I think there are nicer ways to interop in the future, but it takes a good deal of time to get there, and this project is still pretty young.

**Comment by edimetia3d** [comment]
Ok.

Things are indeed more complicated than I thought :sweat_smile: . I'll check IREE and the LLVM discussion to find more.

I guess it's better to get my things to work locally first for now and learn more about MLIR/LLVM to catch up with the community. 

Thanks again.

**Comment by stellaraccident** [comment]
There is no shame in patching something together and then talking about that. It's not that hard to make these things work for a one off when you can copy files around and script around the build a bit. The project infra is just really young and needs more time to evolve.

**Comment by stellaraccident** [comment]
I'm going to go ahead and re-open this because it has a good record of work that needs to be done.

**Comment by stellaraccident** [comment]
On the python side, the npcomp distribution now consists of namespace packages, and it embeds the MLIR Python API vs including it side by side. That wasn't the highest priority thing needed but was important to goals I have.
