### ISSUE TITLE
Installing pre-built binaries

### ISSUE THREAD

**Issue by vincent-mayer** [llvm/torch-mlir#3043]
Hi,

I was wondering why there is no release of pre-built binaries existent after 2024-01-27 and whether this will be resumed again?

Thanks!

**Comment by stellaraccident** [comment]
As part of the publicized attack vectors on self hosted runners and tokens, I no longer wanted to have personal exposure with assets/infra tied to me (the prior project maintainers had handed these things over to me last year and I will admit that I was uncomfortable even then, but the attacks prompted me to set a deadline and remove myself from the loop).

@sjain-stanford did some work to attempt to stand releases up using only GH hosted runners and tokens here: https://github.com/llvm/torch-mlir-release

It appears that they only ran once. Not sure if that was intentional or just got busy before scheduling.

The primary project I work on (IREE) takes a compile time dep vs a runtime/wheel dep on the project. I'm very open to others taking up the torch for binaries.

**Comment by stellaraccident** [comment]
Ah I see, it accumulates all of the dev wheels into one "release": https://github.com/llvm/torch-mlir-release/releases

**Comment by sjain-stanford** [comment]
> Ah I see, it accumulates all of the dev wheels into one "release":

@stellaraccident That's correct, as you can see [here](https://github.com/llvm/torch-mlir-release/blob/main/.github/workflows/buildReleaseAndPublish.yml#L71-L72), we've set it to update the same release, and potentially overwrite if the asset name is the same (this avoids accumulating the same torch binary multiple times between bumps). This was needed because we went with the [expanded_assets hosting](https://github.com/llvm/torch-mlir-release/releases/expanded_assets/dev-wheels) which would've required the release name to be updated each time if we went with separate releases.

**Comment by sjain-stanford** [comment]
@vincent-mayer TLDR; you should be able to install torch-mlir from binary as mentioned on the [README](https://github.com/llvm/torch-mlir-release?tab=readme-ov-file) - let us know if you hit issues. I realize we need to update the torch-mlir readme to replace any mentions of the old binary release with the new one.

**Comment by vincent-mayer** [comment]
That's exactly what I was looking for, thanks @stellaraccident and @sjain-stanford!
