### ISSUE TITLE
Is m_TorchConstantFloat planned

### ISSUE THREAD

**Issue by anupgangwar** [llvm/torch-mlir#497]
Hi,

Is there a plan to add 'm_TorchConstantFloat' similar to 'm_TorchConstantInt'? This is needed for a couple of lowerings.

@ramiro050 Can you comment?

Thanks,
Anup

**Comment by ramiro050** [comment]
Hi @anupgangwar,

We tend to only add functions as they are needed, so if your lowerings require `m_TorchConstantFloat` feel free to add it as part of one of your lowering PRs (this will serve as a test for it). The implementation should be straight forward. You can just do what is done for the Int case:

https://github.com/llvm/torch-mlir/blob/d8ba68119e5b9ff14b2240f0f282643317b5e160/include/torch-mlir/Dialect/Torch/IR/TorchOps.h#L32-L54

The only main difference is that the result type should be a `double` because `float`s in PyTorch are 64-bit, and to access the double, you need to use `convertToDouble()` (https://llvm.org/doxygen/classllvm_1_1APFloat.html#a37733c4c22afc6a48194783dbd25487c)

```cpp
  *bind_value = constantFloat.value().convertToDouble();
```

Happy to help if you run into any issues!

**Comment by anupgangwar** [comment]
Thanks for the quick turn-around, will do the needful.

Anup

**Comment by anupgangwar** [comment]
See that this got implemented before my commit, closing.
