### ISSUE TITLE
Tosa backend failed with assert

### ISSUE THREAD

**Issue by cathyzhyi** [llvm/torch-mlir#512]
Tosa backend fails for a new test added in https://github.com/llvm/torch-mlir/pull/503. The torch dialect IR generated by the test is the following:
```
func @forward(%arg0: !torch.vtensor<[5,4,3,3,1],f32> loc(unknown), %arg1: !torch.vtensor<[?,3,1,2],f32> loc(unknown)) -> !torch.vtensor<[5,?,3,3,2],f32> {
  %0 = torch.aten.mul.Tensor %arg0, %arg1 : !torch.vtensor<[5,4,3,3,1],f32>, !torch.vtensor<[?,3,1,2],f32> -> !torch.vtensor<[5,?,3,3,2],f32>
  return %0 : !torch.vtensor<[5,?,3,3,2],f32>
}
```
Tosa backend would generate
```
func @forward(%arg0: tensor<5x4x3x3x1xf32> loc(unknown), %arg1: tensor<?x3x1x2xf32> loc(unknown)) -> tensor<5x?x3x3x2xf32> {
  %0 = "tosa.mul"(%arg0, %arg1) {shift = 0 : i32} : (tensor<5x4x3x3x1xf32>, tensor<?x3x1x2xf32>) -> tensor<5x?x3x3x2xf32>
  return %0 : tensor<5x?x3x3x2xf32>
}
```
`mlir-opt -tosa-to-linalg tosa.mlir` would crash with assert `const T &llvm::ArrayRef<long>::operator[](size_t) const [T = long]: Assertion Index < Length && "Invalid index!"' failed.`
backtrace:
```
#10 0x0000000000793f39 llvm::ArrayRef<long>::operator[](unsigned long) const llvm/include/llvm/ADT/ArrayRef.h:0:7
#11 0x000000000201ed4a findIntermediateShape(llvm::ArrayRef<long>, llvm::ArrayRef<long>, llvm::SmallVector<long, 6u>&, bool) llvm-project/mlir/lib/Conversion/TosaToLinalg/TosaToLinalg.cpp:941:20
#12 0x0000000002020f59 (anonymous namespace)::ReshapeConverterCollapseExpand::matchAndRewrite(mlir::tosa::ReshapeOp, mlir::tosa::ReshapeOpAdaptor, mlir::ConversionPatternRewriter&) const llvm-project/mlir/lib/Conversion/TosaToLinalg/TosaToLinalg.cpp:1137:9
#13 0x0000000002042500 mlir::OpConversionPattern<mlir::tosa::ReshapeOp>::matchAndRewrite(mlir::Operation*, llvm::ArrayRef<mlir::Value>, mlir::ConversionPatternRewriter&) const llvm-project/mlir/include/mlir/Transforms/DialectConversion.h:424:12
#14 0x0000000002a1bcc3 mlir::ConversionPattern::matchAndRewrite(mlir::Operation*, mlir::PatternRewriter&) const llvm-project/mlir/lib/Transforms/Utils/DialectConversion.cpp:1701:10
```

**Comment by cathyzhyi** [comment]
@sjarus could you help to take a look if the tosa IR looks correct to you? I suspect it's an issue with tosa-to-linalg but could you double check? Thanks!

**Comment by sjarus** [comment]
This is a tricky broadcasting case. I actually hit this same error signature a short while ago while exercising my in-development Matmul/Mm/Bmm legalization code, where there's a need to potentially reshape both inputs, do the matmul and reshape outputs... and reshape of '?' dims is undefined. 

I worked around it by using the CreateOpAndInfer construct in Tosa-To-LinAlg that's also implemented in include/torch-mlir/Conversion/TorchToTosa/TosaLegalizeUtils.h . This should work... but I have found there's at least one bug in this that miscomputes inferred output shape though it shouldn't impact the behavior of this case. 

For this case itself, there's also a fundamental issue with the output shape - dim1 cannot be any number other than 4 since it needs to resolve 4 vs '?' and thus the latter can legally be only a 4 or a broadcasting 1. How does the Torch resolve output shape to 5x?x3x3x2 rather than 5x4x3x3x2 ? If Torch offers 5x4x3x3x2 as output shape, this failure should not occur.

**Comment by cathyzhyi** [comment]
> 1. How does the Torch resolve output shape to 5x?x3x3x2 rather than 5x4x3x3x2 ? If Torch offers 5x4x3x3x2 as output shape, this failure should not occur.
yea, I could change the code to infer shape based on valid user input, in this case 4 or a broadcasting 1 for dim1. I was hesitating to do that because user might give an invalid input and we would be inferring something that might not be true at runtime. However, I realize I've already be doing that by adding the static shape for broadcasting ops already so this might still be ok for now. 

Thanks for the detailed reply!

**Comment by sjarus** [comment]
Right, for this test I think the straightforward resolution is to pass the legally resolvable output shape 5x4x3x3x2. Then it should work fine. 

More generally, it's possible to have input shapes as 5x1x3x3x1 and ?x3x1x2 which would result in 5x?x3x3x2 as the legal output shape.  In this case TOSA-to-LinAlg should at least just say it cannot process dynamic shapes, but not crash. However such a self-contained test would not be useful for e2e since it's not fundamentally compile time resolvable.

**Comment by cathyzhyi** [comment]
Yea, will change the test. thanks again!
