### ISSUE TITLE
Missing support for importing node prim::Constant with list type

### ISSUE THREAD

**Issue by henrytwo** [llvm/torch-mlir#555]
I was trying out torch-mlir with LTC using the TorchScript backend but ran into an error when performing a basic transpose operation using a modified version of the `tanh` example script:

```
LAZY GRAPH
graph(%p0 : Tensor):
  %1 : int[] = prim::Constant[value=[1, 0]]()
  %2 : int[] = prim::Constant[value=[1, 0]]()
  %3 : Tensor = aten::permute(%p0, %2)
  return (%3)

error: unhandled prim::Constant node: %1 : int[] = prim::Constant[value=[1, 0]]()

Traceback (most recent call last):
  File "repro_prim_list_error.py", line 27, in <module>
    mb.import_function(script_function)
RuntimeError: see diagnostics
```

To reproduce:
```python
import lazy_tensor_core as ltc
import torch
from torch._C import CompilationUnit
from torch_mlir.dialects.torch.importer.jit_ir import ModuleBuilder

ltc._LAZYC._ltc_init_ts_backend()
device = torch.device('lazy')
dtype = torch.float32

x = torch.randn((4, 5), device=device, dtype=dtype)

# Capture lazy computation and convert to TorchScript IR
graph_str = ltc._LAZYC._get_ltc_tensors_backend([
    x.T
])

print("LAZY GRAPH")
print(graph_str)
graph = torch._C.parse_ir(graph_str)

# Create a torch.jit.ScriptFunction out of the graph
cu = CompilationUnit()
func_name = 'my_method'
script_function = cu.create_function(func_name, graph)

mb = ModuleBuilder()
mb.import_function(script_function)

print(mb.module)
```

It looks like the error stems from the `import_function` call of `ModuleBuilder`, which is part of `torch-mlir`. Currently my hacky solution around this problem is to make the SSA values corresponding to primitive lists a parameter, but I'm wondering if there is a _better_ way to do this.

**Comment by cathyzhyi** [comment]
Hey Henry, thanks for your interest in the project! 
The issue you are hitting is because we are still missing support for importing `prim::Constant` node with List type.  The error msg you are seeing is from the node importer https://github.com/llvm/torch-mlir/blob/0cb216a1adcdcc8c948503c0f856604997d13c1d/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/node_importer.cpp#L185. We would need to add a ` else if (auto listType = output->type()->cast<c10::ListType>()) {` branch to handle the constant list case. We currently don't have Constant List type in torch dialect so, I would suggest creating a `prim::ListConstruct` node instead. The way to construct `prim::ListConstruct` would be similar to the code here in the value importer where we import a list value from TS 
https://github.com/llvm/torch-mlir/blob/0cb216a1adcdcc8c948503c0f856604997d13c1d/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/ivalue_importer.cpp#L268
We need to figure out all the list element from the original `prim::Constant[value=[1, 0]]()` node and pass those elements to `prim::ListConstruct`.
Let me know if you would like to help with implementing this.

**Comment by cathyzhyi** [comment]
we could leave this open until someone got time to implement it.

**Comment by henrytwo** [comment]
@cathyzhyi I think I'm going to try to take a shot at implementing this, since I need the functionality for my project. I'll let you know if I run into any issues :)

**Comment by cathyzhyi** [comment]
> @cathyzhyi I think I'm going to try to take a shot at implementing this, since I need the functionality for my project. I'll let you know if I run into any issues :)

Great! Thanks a lot!

**Comment by henrytwo** [comment]
If I have something like this in the IR:
```
%1 : int[] = prim::Constant[value=[1, 2, 3]]()
```

What should the corresponding MLIR look like? Would it be something like:
```
%0 = torch.prim.ListConstruct  {value = [1, 2, 3]} : () -> !torch.list<!torch.int>
``` 

I saw that in some existing examples, the individual list values are passed in as arguments to the `ListConstruct` operation (https://github.com/Cerebras/torch-mlir-private/blob/090243888259e6f24df355fdd0aaf679cdc9e660/test/Conversion/TorchToLinalg/pooling.mlir#L21), so that's why I'm wondering.

**Comment by cathyzhyi** [comment]
Hey Henry, for `%1 : int[] = prim::Constant[value=[1, 2, 3]]()` the instructions generated should look like 
```
%kernel_size = torch.prim.ListConstruct %int1, %int2, %int3 : (!torch.int, !torch.int,  !torch.int) -> !torch.list<!torch.int>
```
you need to pass all elements which are MLIR values as the operands of the instruction. You could refer to the code here https://github.com/llvm/torch-mlir/blob/0cb216a1adcdcc8c948503c0f856604997d13c1d/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/ivalue_importer.cpp#L269-L278.  

To get the individual elements out of the `value` attribute from the torch::jit::node you can refer to `torch_mlir::importAttribute` https://github.com/llvm/torch-mlir/blob/127c7d8e27ede211af77392b5277ba06fb515fb7/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/torch_to_mlir_utils.cpp#L316. However, this case it's a bit special and can't be handled by this method directly because the  `torch::jit::AttributeKind` would be `torch::jit::AttributeKind::ival` which is a c10::ivalue.  You can import the list ivalue same way as here https://github.com/llvm/torch-mlir/blob/127c7d8e27ede211af77392b5277ba06fb515fb7/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/ivalue_importer.cpp#L269-L273. However, the result won't be a MLIRAttribute (as expected by the return type of torch_mlir::importAttribute) but `std::vector<MlirValue>`. So I would recommend creating another method called something like `importAttributeAsMlirValues` just for this case.

**Comment by henrytwo** [comment]
I just reread your previous comments and I _think_ you're saying the new `importAttributeAsMlirValues` method is supposed to be used instead of `importAttribute`, right? That way the generated `MlirValue`s can be passed in during construction of `torch.prim.ListConstruct`.

So the signature could be something like: `std::vector<MlirValue> importAttributeAsMlirValues(MlirLocation loc,
                                          torch::jit::Node *node,
                                          c10::Symbol symbol, 
         MlirBlock block,
                              MlirContext context)`

**Comment by henrytwo** [comment]
Looking at the [public interface in `ivalue_importer.h`](https://github.com/llvm/torch-mlir/blob/main/python/torch_mlir/dialects/torch/importer/jit_ir/csrc/ivalue_importer.h#L28-L29), it looks like the only method exposed has a void return value, but I updated that to `MlirValue` and was able to get it to work in a similar way to what you just described. Thanks for the help!

Is there documentation with guidelines on running/adding unit tests, and automatically formatting code to comply with the style guide before I open a PR? I looked through the README file but didn't see any

**Comment by cathyzhyi** [comment]
We mostly just follow the llvm coding convention. There are some guidelines here https://github.com/llvm/torch-mlir/wiki/Torch-ops-E2E-implementation#delivering-code. For unit tests, you can refer to examples here https://github.com/llvm/torch-mlir/blob/main/test/python/importer/jit_ir/node_import/prim.py. The testing for importers are in test/python/importer.

**Comment by henrytwo** [comment]
> For unit tests, you can refer to examples here https://github.com/llvm/torch-mlir/blob/main/test/python/importer/jit_ir/node_import/prim.py. The testing for importers are in test/python/importer.

I tried writing a test based on the examples you sent here, but I think since it uses `@torch.jit.script`, the list elements are individually assigned SSA values and then passed into `prim::ListConstruct` in the TorchScript IR.

Do you know of any way to "force" it to generate a `prim::Constant` with list type instead? A possible solution would be to hardcode some TS IR that contains a constant list, but that doesn't seem consistent with the other tests.

Test script:
```python
import torch
from torch_mlir.dialects.torch.importer.jit_ir import ModuleBuilder

mb = ModuleBuilder()

@mb.import_function
@torch.jit.script
def prim_List():
    return [1, 2, 3]

print(prim_List.graph)
mb.module.operation.print()
```

Output:
```
graph():
  %0 : int = prim::Constant[value=1]()
  %1 : int = prim::Constant[value=2]() 
  %2 : int = prim::Constant[value=3]() 
  %3 : int[] = prim::ListConstruct(%0, %1, %2)  # We want this to be `prim::Constant[value=[1, 2, 3]]()`
  return (%3)

module  {
  func @__torch__.prim_List() -> !torch.list<!torch.int> {
    %int1 = torch.constant.int 1
    %int2 = torch.constant.int 2
    %int3 = torch.constant.int 3
    %0 = torch.prim.ListConstruct %int1, %int2, %int3 : (!torch.int, !torch.int, !torch.int) -> !torch.list<!torch.int>
    return %0 : !torch.list<!torch.int>
  }
}
```

**Comment by cathyzhyi** [comment]
> A possible solution would be to hardcode some TS IR that contains a constant list, but that doesn't seem consistent with the other tests.
I think that's a good idea as we have more control over what specific TS IR we want to test. Please go ahead with whatever you have in mind for now.
