### ISSUE TITLE
Question regarding usage of aten.ones in MiniLMSequenceClassificationStatic

### ISSUE THREAD

**Issue by anupgangwar** [llvm/torch-mlir#755]
Hi,

In the MiniLMSequenceClassification static model, we have an aten.ones as shown below:

  ```
  %110 = torch.prim.NumToTensor.Scalar %int1 : !torch.int -> !torch.vtensor<[],si32> 
    %111 = torch.prim.NumToTensor.Scalar %int7 : !torch.int -> !torch.vtensor<[],si32>   
    %112 = torch.aten.add.Tensor %111, %107, %int1 : !torch.vtensor<[],si32>, !torch.vtensor<[],si32>, !torch.int -> !torch.vtensor<[],si32> 
    %113 = torch.aten.Int.Tensor %112 : !torch.vtensor<[],si32> -> !torch.int 
    %114 = torch.prim.ListConstruct %int1, %113 : (!torch.int, !torch.int) -> !torch.list<int> 
    %115 = torch.aten.ones %114, %int6, %none, %cpu, %false : !torch.list<int>, !torch.int, !torch.none, !torch.Device, !torch.bool -> !torch.vtensor<[1,?],f32> 
    ............
    %120 = torch.aten.slice.Tensor %115, %int0, %int0, %int9223372036854775807, %int1 : !torch.vtensor<[1,?],f32>, !torch.int, !torch.int, !torch.int, !torch.int -> !torch.vtensor<[1,?],f32> 
```

Is there a way to deal with this aten.ones at the Torchscript level? This is presenting some lowering issues in TorchToTosa and it is also not clear as to why the inputs to slice (%120) are being constructed this way.

**Comment by anupgangwar** [comment]
Tagging @sjarus @ramiro050.

**Comment by sjarus** [comment]
Thanks for the writeup @anupgangwar! The problem here is that the ListConstruct is built from two scalars - the int1 and the result of the aten.add.Tensor which is really a scalar addition operation. 

If it was just the ListConstruct followed by slice we could replace that with a tosa.concat followed by tosa.slice, as inefficient as that is. But real dealbreaker is the presence of the aten.ones in between . The existing legalization of AtenOnesOp in TOSA deals with const values, but the add here generates non const content. It's unclear what purpose the aten.ones here serves, and in general why there's a list construct followed by a slice.

**Comment by silvasean** [comment]
This seems like a very peculiar pattern for getting a tensor of ones of a specific shape.

It appears that it is using a tensor to calculate a shape for some reason. I would recommend adding folders for these ops:

```
%110 = torch.prim.NumToTensor.Scalar %int1 : !torch.int -> !torch.vtensor<[],si32> 
  %111 = torch.prim.NumToTensor.Scalar %int7 : !torch.int -> !torch.vtensor<[],si32>   
  %112 = torch.aten.add.Tensor %111, %107, %int1 : !torch.vtensor<[],si32>, !torch.vtensor<[],si32>, !torch.int -> !torch.vtensor<[],si32> 
  %113 = torch.aten.Int.Tensor %112 : !torch.vtensor<[],si32> -> !torch.int 
```

This should then reduce the torch.aten.ones to static shape. For torch.aten.add.Tensor, I would recommend limiting the folding to the Rank-0 case for now and reusing some of the folders for torch.aten.add.int.

**Comment by silvasean** [comment]
We greatly improved these scalar tensor folders, so this should be fixed now.
