### ISSUE TITLE
Cannot intercept aten::conv2d when dispatching through backend keys

### ISSUE THREAD

**Issue by stellaraccident** [llvm/torch-mlir#86]
When using a backend dispatch key (i.e. PrivateUse3), aten::conv2d calls are never recorded; however, when using AutogradPrivateUse3, they are (but this has other problems). conv is special in a number of ways and need to check with PT devs regarding how to resolve.

**Comment by byronyi** [comment]
Could https://github.com/pytorch/pytorch/pull/23562 be relevant?

**Comment by ailzhang** [comment]
Hmmm I probably didn't fully get what you meant by "when using AutogradPrivateUse3 instead of PrivateUse3, aten::conv2d is recorded". IIRC those two keys are only different in the sense that one has autograd related setup in its kernel and the other doesn't. 
Do you want to get aten::conv2d (the decomposed ops from convolution) or a generic convolution here?
